### ISSUE TITLE
考虑Lo-dash替换underscore

### ISSUE THREAD

**Issue by feibyte** [acelan86/ESinaProject#6]
backbone依赖underscore。Lo-dash兼容underscore，比它功能更强大。说是100%兼容，当然也有些许不同。

**Comment by acelan86** [comment]
Lo-dash的更强大的功能在项目开发中的用处是？其实如果不是选了backbone，backbone强依赖underscore，我不会引入underscore的功能
因为我认为一个项目只用一个lib才是干净的，不至于使用上的混乱，这里先择的lib是jq或者是zepto
而且，即使是现在引入了underscore，我也觉得在业务开发中避免用到 _.（即underscore的任何api）。

以上
